apiVersion: v1
appVersion: "1.0"
description: A Helm chart for installing cert-manager-webhook-loopia in Kubernetes
name: cert-manager-webhook-loopia
version: 0.1.0
maintainers:
  - name: Henrik Nilsson, Identitry
    url: https://github.com/Identitry/cert-manager-webhook-loopia